#!/bin/bash

# Name: blew - 'B'uild tools for 'Lew'Engine
# Description: Starts the project using setup, build, install, test, etc. options
# Options: 
# 	-b/--build:     Build the project for the specified target and method (app, test, ..)
#	-s/--setup:     Install packages and prepare environment for all the methods
#	-t/--test:      Run tests included or apart from the build option
#	-x/--execute:   Execute the application, UI or the current state
#   -i/--install:   Instal the current state of the project on the machine
#   -c/--clean:     Clean the workspace from generated builds, logs, containers, etc.
